image: continuumio/miniconda3:latest

before_script:
  - conda update -n base conda
  - conda env create -n xorca -f environment.yml
  - source activate xorca
  - python setup.py install

pytest_and_coverage:
  stage: test
  script:
    - pytest -v --cov --cov-report="term-missing" xorca/tests/
