image: continuumio/miniconda3:latest

before_script:
  - conda update -n base conda
  - conda env create -n xorca -f environment.yml
  - source activate xorca
  - python setup.py install

simple:
  stage: test
  script:
    - pytest xorca/tests/

detailed:
  stage: test
  script:
    - pytest -v --cov=xorca/ --cov-report term-missing xorca/tests/
