image: continuumio/miniconda3:latest

before_script:
  - conda update -n base conda
  - conda env create -n xorca -f environment.yml
  - source activate xorca
  - pip install -e .
  - GIT_LFS_SKIP_SMUDGE=1 git submodule init
  - GIT_LFS_SKIP_SMUDGE=1 git submodule update
  - (cd example-data; git lfs pull -I="meshmask/*.nc";)

pytest_and_coverage:
  stage: test
  script:
    - flake8 xorca/
    - pytest -v --cov=xorca --cov-report="term-missing" xorca/tests/
