name: xorca
channels:
  - conda-forge
dependencies:
  - python=3
  - blas
  - coverage
  - dask
  - flake8
  - git-lfs
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - xarray
  - pip:
      - codecov
      - git+https://github.com/xgcm/xgcm.git@1361e8df0024d4f3f7f4d984047370469425473b
